parameters:
  - name: mySteps
    type: stepList
    default: []

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - task: MyTelemetryReporter@1
    - ${{ each step in parameters.mySteps }}:
      - ${{ step }}
    - task: MyVirusScanner@1
